/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rw.church.view;

/**
 *
 * @author nshut
 */
public class Dashboard extends javax.swing.JFrame {

    private String currentUsername;
    private String currentRole;

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Church Member & Tithe System - Dashboard");
        applyStyles();
    }

    public Dashboard(String username) {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Church Member & Tithe System - Dashboard");
        jLabel1.setText("Welcome, " + username + "  |  Church Member & Tithe System");
        applyStyles();
    }

    public Dashboard(String username, String role) {
        initComponents();
        setLocationRelativeTo(null);
        this.currentUsername = username;
        this.currentRole = role;
        applyRoleAccess();
        applyStyles();
    }

    private void applyStyles() {
        getContentPane().setBackground(new java.awt.Color(240, 245, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
        jLabel1.setForeground(new java.awt.Color(51, 102, 153));
        for (javax.swing.JButton btn : new javax.swing.JButton[]{membersBtn, cellGroupBtn, serviceBtn, logoutBtn, contributionBtn, usersBtn, reportsBtn, myProfileBtn}) {
            btn.setBackground(new java.awt.Color(51, 102, 153));
            btn.setForeground(java.awt.Color.WHITE);
            btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
            btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        membersBtn = new javax.swing.JButton();
        cellGroupBtn = new javax.swing.JButton();
        serviceBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        contributionBtn = new javax.swing.JButton();
        usersBtn = new javax.swing.JButton();
        reportsBtn = new javax.swing.JButton();
        myProfileBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Church Member & Tithe Managment System");

        membersBtn.setText("Manage Members");
        membersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                membersBtnActionPerformed(evt);
            }
        });

        cellGroupBtn.setText("Manage Cell Groups");
        cellGroupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cellGroupBtnActionPerformed(evt);
            }
        });

        serviceBtn.setText("Manage Services");
        serviceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceBtnActionPerformed(evt);
            }
        });

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        contributionBtn.setText("Manage Contributions");
        contributionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contributionBtnActionPerformed(evt);
            }
        });

        usersBtn.setText("Manage Users");
        usersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersBtnActionPerformed(evt);
            }
        });

        reportsBtn.setText("Reports");
        reportsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsBtnActionPerformed(evt);
            }
        });

        myProfileBtn.setText("My Profile");
        myProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myProfileBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(264, 264, 264))
            .addGroup(layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cellGroupBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contributionBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(serviceBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(membersBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usersBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reportsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(myProfileBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(cellGroupBtn)
                .addGap(31, 31, 31)
                .addComponent(membersBtn)
                .addGap(35, 35, 35)
                .addComponent(contributionBtn)
                .addGap(30, 30, 30)
                .addComponent(serviceBtn)
                .addGap(37, 37, 37)
                .addComponent(usersBtn)
                .addGap(41, 41, 41)
                .addComponent(reportsBtn)
                .addGap(30, 30, 30)
                .addComponent(myProfileBtn)
                .addGap(30, 30, 30)
                .addComponent(logoutBtn)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cellGroupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cellGroupBtnActionPerformed
        // TODO add your handling code here:
        new CellGroupModule().setVisible(true);
    }//GEN-LAST:event_cellGroupBtnActionPerformed

    private void serviceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceBtnActionPerformed
        // TODO add your handling code here:
        new ServiceModule().setVisible(true);
    }//GEN-LAST:event_serviceBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout", javax.swing.JOptionPane.YES_NO_OPTION);
if (confirm == javax.swing.JOptionPane.YES_OPTION) {    
    new LoginForm().setVisible(true);    
    this.dispose();
} 
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void membersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_membersBtnActionPerformed
        // TODO add your handling code here:
        
        MemberModule memberModule = new MemberModule();
        memberModule.setVisible(true);
        memberModule.setLocationRelativeTo(null);
    }//GEN-LAST:event_membersBtnActionPerformed

    private void contributionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contributionBtnActionPerformed
        // TODO add your handling code here:
        new ContributionModule(currentUsername).setVisible(true);
    }//GEN-LAST:event_contributionBtnActionPerformed

    private void usersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersBtnActionPerformed
        // TODO add your handling code here:
        new UserModule().setVisible(true); 
    }//GEN-LAST:event_usersBtnActionPerformed

    private void reportsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsBtnActionPerformed
        // TODO add your handling code here:
        new ReportModule().setVisible(true);
    }//GEN-LAST:event_reportsBtnActionPerformed

    private void myProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myProfileBtnActionPerformed
        if (currentUsername != null) {
            new MemberProfileForm(currentUsername).setVisible(true);
        }
    }//GEN-LAST:event_myProfileBtnActionPerformed

    private void applyRoleAccess() {
        if ("ADMIN".equalsIgnoreCase(currentRole)) {
            // Admin sees all buttons
            membersBtn.setVisible(true);
            cellGroupBtn.setVisible(true);
            serviceBtn.setVisible(true);
            usersBtn.setVisible(true);
            reportsBtn.setVisible(true);
            contributionBtn.setVisible(true);
            myProfileBtn.setVisible(true);
        } else {
            // Regular member — hide admin-only buttons
            membersBtn.setVisible(false);
            cellGroupBtn.setVisible(false);
            serviceBtn.setVisible(false);
            usersBtn.setVisible(false);
            reportsBtn.setVisible(false);
            // Member can see their contributions and profile
            contributionBtn.setVisible(true);
            myProfileBtn.setVisible(true);
        }
        jLabel1.setText("Welcome, " + currentUsername
            + " | Role: " + currentRole
            + " | Church Member & Tithe System");
        setTitle("Church Member & Tithe System - Dashboard");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cellGroupBtn;
    private javax.swing.JButton contributionBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton membersBtn;
    private javax.swing.JButton myProfileBtn;
    private javax.swing.JButton reportsBtn;
    private javax.swing.JButton serviceBtn;
    private javax.swing.JButton usersBtn;
    // End of variables declaration//GEN-END:variables
}
