/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rw.church.view;

/**
 *
 * @author nshut
 */
public class ReportModule extends javax.swing.JFrame {

    /**
     * Creates new form ReportModule
     */
    private javax.swing.JButton backBtn;

    public ReportModule() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Reports & Export");
        getContentPane().setBackground(new java.awt.Color(240, 245, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
        jLabel1.setForeground(new java.awt.Color(51, 102, 153));
        for (javax.swing.JLabel lbl : new javax.swing.JLabel[]{jLabel2, jLabel3}) {
            lbl.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        }
        for (javax.swing.JButton btn : new javax.swing.JButton[]{exportPdfBtn, exportExcelBtn}) {
            btn.setBackground(new java.awt.Color(51, 102, 153));
            btn.setForeground(java.awt.Color.WHITE);
            btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
            btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        }
        for (javax.swing.JTextField tf : new javax.swing.JTextField[]{monthTxt, yearTxt}) {
            tf.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
            tf.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 153)),
                javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4)));
        }
        backBtn = new javax.swing.JButton("Back to Dashboard");
        backBtn.setBackground(new java.awt.Color(51, 102, 153));
        backBtn.setForeground(java.awt.Color.WHITE);
        backBtn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        javax.swing.JPanel mainWrapper = new javax.swing.JPanel(new java.awt.BorderLayout());
        mainWrapper.setBackground(new java.awt.Color(240, 245, 255));
        mainWrapper.add(getContentPane(), java.awt.BorderLayout.CENTER);
        mainWrapper.add(backBtn, java.awt.BorderLayout.SOUTH);
        setContentPane(mainWrapper);
        pack();
    }

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        monthTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        yearTxt = new javax.swing.JTextField();
        exportPdfBtn = new javax.swing.JButton();
        exportExcelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Reports & Export");

        jLabel2.setText("Month (1-12):");

        jLabel3.setText("Year (e.g. 2026):");

        exportPdfBtn.setText("Export PDF — Monthly Contributions");
        exportPdfBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportPdfBtnActionPerformed(evt);
            }
        });

        exportExcelBtn.setText("Export Excel — Cell Group Summary");
        exportExcelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportExcelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(monthTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(yearTxt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(exportPdfBtn)
                        .addGap(153, 153, 153)
                        .addComponent(exportExcelBtn)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(monthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(yearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(144, 144, 144)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exportPdfBtn)
                    .addComponent(exportExcelBtn))
                .addContainerGap(344, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exportExcelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportExcelBtnActionPerformed
        // TODO add your handling code here:
        try {
    java.rmi.registry.Registry registry = java.rmi.registry.LocateRegistry.getRegistry("127.0.0.1", 5000);
    rw.church.service.CellGroupService service =
        (rw.church.service.CellGroupService) registry.lookup("CellGroupService");
    java.util.List<rw.church.model.CellGroup> groups = service.findAllCellGroups();

    rw.church.service.MemberService mSvc =
        (rw.church.service.MemberService) registry.lookup("MemberService");
    java.util.List<rw.church.model.Member> allMembers = mSvc.findAllMembers();

    org.apache.poi.xssf.usermodel.XSSFWorkbook workbook = new org.apache.poi.xssf.usermodel.XSSFWorkbook();
    org.apache.poi.ss.usermodel.Sheet sheet = workbook.createSheet("Cell Group Summary");

    org.apache.poi.ss.usermodel.Row headerRow = sheet.createRow(0);
    headerRow.createCell(0).setCellValue("Cell Group");
    headerRow.createCell(1).setCellValue("Leader");
    headerRow.createCell(2).setCellValue("Total Members");
    headerRow.createCell(3).setCellValue("Members");

    int rowIndex = 1;
    for (rw.church.model.CellGroup cg : groups) {
        java.util.List<String> memberNames = new java.util.ArrayList<>();
        for (rw.church.model.Member m : allMembers) {
            if (m.getCellGroup() != null && m.getCellGroup().getId() == cg.getId()) {
                memberNames.add(m.getFullName());
            }
        }
        org.apache.poi.ss.usermodel.Row row = sheet.createRow(rowIndex++);
        row.createCell(0).setCellValue(cg.getName());
        row.createCell(1).setCellValue(cg.getLeader());
        row.createCell(2).setCellValue(memberNames.size());
        row.createCell(3).setCellValue(String.join(", ", memberNames));
    }

    String filePath = System.getProperty("user.home") + "\\Desktop\\CellGroup_Summary.xlsx";
    java.io.FileOutputStream fos = new java.io.FileOutputStream(filePath);
    workbook.write(fos); fos.close(); workbook.close();

    javax.swing.JOptionPane.showMessageDialog(this,
        "Excel exported: CellGroup_Summary.xlsx saved to Desktop",
        "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
} catch (Exception ex) {
    ex.printStackTrace();
    javax.swing.JOptionPane.showMessageDialog(this,
        "Excel export failed: " + ex.getMessage(),
        "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
} 
    }//GEN-LAST:event_exportExcelBtnActionPerformed

    private void exportPdfBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportPdfBtnActionPerformed
        // TODO add your handling code here:
        try {
    int month = Integer.parseInt(monthTxt.getText().trim());
    int year = Integer.parseInt(yearTxt.getText().trim());

    java.rmi.registry.Registry registry = java.rmi.registry.LocateRegistry.getRegistry("127.0.0.1", 5000);
    rw.church.service.ContributionService service =
        (rw.church.service.ContributionService) registry.lookup("ContributionService");
    java.util.List<rw.church.model.Contribution> list = service.getContributionsByMonth(month, year);

    com.itextpdf.text.Document pdfDoc = new com.itextpdf.text.Document();
    String filePath = "Monthly_Report_" + month + "_" + year + ".pdf";
    com.itextpdf.text.pdf.PdfWriter.getInstance(pdfDoc, new java.io.FileOutputStream(filePath));
    pdfDoc.open();

    com.itextpdf.text.Font titleFont = new com.itextpdf.text.Font(
        com.itextpdf.text.Font.FontFamily.HELVETICA, 16, com.itextpdf.text.Font.BOLD);
    pdfDoc.add(new com.itextpdf.text.Paragraph(
        "Monthly Contribution Report — " + month + "/" + year, titleFont));
    pdfDoc.add(new com.itextpdf.text.Paragraph(" "));

    com.itextpdf.text.pdf.PdfPTable table = new com.itextpdf.text.pdf.PdfPTable(4);
    table.addCell("Member"); table.addCell("Type");
    table.addCell("Amount"); table.addCell("Date");

    for (rw.church.model.Contribution c : list) {
        table.addCell(c.getMember() != null ? c.getMember().getFullName() : "");
        table.addCell(c.getContributionType());
        table.addCell(String.valueOf(c.getAmount()));
        table.addCell(c.getContributionDate() != null ? c.getContributionDate().toString() : "");
    }
    pdfDoc.add(table);
    pdfDoc.close();

    javax.swing.JOptionPane.showMessageDialog(this, "PDF exported: " + filePath,
        "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
} catch (Exception ex) {
    ex.printStackTrace();
    javax.swing.JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(),
        "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
} 
    }//GEN-LAST:event_exportPdfBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportModule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exportExcelBtn;
    private javax.swing.JButton exportPdfBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField monthTxt;
    private javax.swing.JTextField yearTxt;
    // End of variables declaration//GEN-END:variables
}
